# Generated by Django 2.2.6 on 2020-05-31 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='clientes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profile_image', models.ImageField(blank=True, null=True, upload_to='Clientes', verbose_name='Foto de Perfil')),
                ('name', models.CharField(max_length=200, verbose_name='Nombre')),
                ('surname', models.CharField(max_length=200, verbose_name='Apellidos')),
                ('phone', models.CharField(max_length=9, verbose_name='Telefono')),
                ('country', models.CharField(max_length=200, verbose_name='pais')),
                ('is_company', models.BooleanField(blank=True, null=True, verbose_name='Compañia')),
                ('is_blacklisted', models.BooleanField(blank=True, null=True, verbose_name='Lista Negra')),
                ('is_active', models.BooleanField(blank=True, null=True, verbose_name='Activo')),
                ('is_supplier', models.BooleanField(blank=True, null=True, verbose_name='Proveedor')),
                ('is_employee', models.BooleanField(blank=True, null=True, verbose_name='Empleado')),
            ],
            options={
                'verbose_name': 'Contacto',
                'verbose_name_plural': 'Contactos',
            },
        ),
    ]
