# Generated by Django 2.2.6 on 2020-06-15 16:57

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clientes', '0002_auto_20200611_0915'),
        ('productos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Factura',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(default=datetime.datetime(2020, 6, 15, 16, 57, 36, 327413), verbose_name='Fecha emmitida')),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clientes.clientes', verbose_name='cliente')),
            ],
            options={
                'verbose_name': 'factura',
                'verbose_name_plural': 'facturas',
            },
        ),
        migrations.CreateModel(
            name='FacturaLinea',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.IntegerField(verbose_name='cantidad')),
                ('FacturaPerteneciente_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ventas.Factura', verbose_name='lista De producto')),
                ('produtos_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='productos.Product', verbose_name='lista De producto')),
            ],
            options={
                'verbose_name': 'linea de factura',
                'verbose_name_plural': 'lineas de facturas',
            },
        ),
    ]
